# Generated by Django 6.0.3 on 2026-06-29 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('event_type', models.CharField(choices=[('Wedding', 'Wedding'), ('Pre Wedding', 'Pre Wedding'), ('Engagement', 'Engagement'), ('Birthday', 'Birthday'), ('Baby Shoot', 'Baby Shoot'), ('Maternity', 'Maternity'), ('Other', 'Other')], max_length=50)),
                ('event_date', models.DateField()),
                ('location', models.CharField(max_length=200)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
