# Generated by Django 6.0.3 on 2026-06-30 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_gallery_booking'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ['-uploaded_at']},
        ),
    ]
