# Generated by Django 6.0.3 on 2026-06-30 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_gallery_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='album_name',
            field=models.CharField(default='General', max_length=100),
        ),
    ]
